robot_ip: "163.220.51.93"
camera_ids:
  front: '212622063194'
  hand: '145522068277'
# gelsight_ids:
#   tactile_left: "GelSight Mini R0B 2BNK-CE0U: Ge"
#   tactile_right: "GelSight Mini R0B 2BG8-0H3X: Ge"
